/**
 * 공개 가이드 30편의 편집 기준.
 *
 * 기존 원문에서 검색 의도가 겹치는 글은 통합하고, 남길 글에는
 * 독자의 질문·확인 시점·판단 기준·실행 체크리스트를 보강한다.
 * 수치가 자주 바뀌는 가격·보조금은 본문에 고정하지 않고 계산기와
 * 공식 출처에서 다시 확인하도록 안내한다.
 */

const REVIEW_DATE = "2026-08-28";

const SOURCES = {
  teslaSupport: {
    name: "Tesla 지원 대한민국 — 차량·충전·서비스 안내",
    url: "https://www.tesla.com/ko_kr/support",
    accessedAt: REVIEW_DATE,
  },
  teslaModel3: {
    name: "Tesla 대한민국 — Model 3 공식 사양 및 주문 페이지",
    url: "https://www.tesla.com/ko_kr/model3",
    accessedAt: REVIEW_DATE,
  },
  teslaModelY: {
    name: "Tesla 대한민국 — Model Y 공식 사양 및 주문 페이지",
    url: "https://www.tesla.com/ko_kr/modely",
    accessedAt: REVIEW_DATE,
  },
  teslaWarranty: {
    name: "Tesla 지원 대한민국 — 차량 제한 보증",
    url: "https://www.tesla.com/ko_kr/support/vehicle-warranty",
    accessedAt: REVIEW_DATE,
  },
  teslaCharging: {
    name: "Tesla 지원 대한민국 — 수퍼차저 이용 안내",
    url: "https://www.tesla.com/ko_kr/support/charging/supercharging",
    accessedAt: REVIEW_DATE,
  },
  teslaRange: {
    name: "Tesla 지원 대한민국 — 주행 가능 거리와 배터리 관리",
    url: "https://www.tesla.com/ko_kr/support/range",
    accessedAt: REVIEW_DATE,
  },
  teslaAutopilot: {
    name: "Tesla 대한민국 — 오토파일럿 및 운전자 보조 기능",
    url: "https://www.tesla.com/ko_kr/autopilot",
    accessedAt: REVIEW_DATE,
  },
  teslaTestDrive: {
    name: "Tesla 지원 대한민국 — 시승 및 주문 준비 안내",
    url: "https://www.tesla.com/ko_kr/support/test-drive",
    accessedAt: REVIEW_DATE,
  },
  evPortal: {
    name: "무공해차 통합누리집 — 구매보조금 지원 대상·지자체 공고·잔여 물량",
    url: "https://www.ev.or.kr/nportal/main.do",
    accessedAt: REVIEW_DATE,
  },
  environment: {
    name: "환경부 — 무공해차 보급 정책 및 업무처리지침",
    url: "https://www.me.go.kr/home/web/main.do",
    accessedAt: REVIEW_DATE,
  },
  fss: {
    name: "금융감독원 금융상품통합비교공시 — 자동차 금융 비교",
    url: "https://finlife.fss.or.kr/finlife/main/main.do",
    accessedAt: REVIEW_DATE,
  },
  nts: {
    name: "국세청 — 차량 관련 세금 및 사업용 차량 안내",
    url: "https://www.nts.go.kr/nts/main.do",
    accessedAt: REVIEW_DATE,
  },
  car365: {
    name: "자동차365 — 중고차 이력·등록·매매 정보",
    url: "https://www.car365.go.kr/",
    accessedAt: REVIEW_DATE,
  },
  law: {
    name: "국가법령정보센터 — 자동차관리법·소비자 관련 법령",
    url: "https://www.law.go.kr/",
    accessedAt: REVIEW_DATE,
  },
};

const R = {
  "tesla-purchase-process-for-beginners": {
    category: "구매 가이드",
    title: "테슬라 계약 전부터 인도까지, 구매 순서와 확인할 항목",
    description: "예산·충전 환경·보조금 접수·보험·인도 점검을 어떤 순서로 확인해야 시행착오를 줄일 수 있는지 정리합니다.",
    question: "테슬라 구매는 어떤 순서로 준비해야 빠뜨리는 항목이 없을까?",
    stage: "첫 견적을 보기 전",
    needLevel: "매우 높음",
    intent: "차량 가격만 확인한 뒤 계약해도 되는지, 계약 전후에 어떤 일을 누가 처리하는지 알고 싶은 사람",
    answer: "차량 선택보다 먼저 월 예산과 충전 환경을 확정하고, 그다음 보조금 자격과 접수 일정을 확인해야 합니다. 주문 이후에는 출고 일정에 맞춰 보험·등록·결제 수단을 준비하고, 인도일에는 차량 상태와 계정 연동을 확인하는 순서가 안전합니다.",
    why: "테슬라 주문은 온라인에서 빠르게 끝나지만 보조금과 보험, 충전 준비는 서로 다른 기관과 일정에 걸쳐 진행됩니다. 순서를 거꾸로 잡으면 출고가 빨라져도 보조금 접수나 자금 집행이 따라오지 못할 수 있습니다.",
    keyPoints: ["계약 전 월 예산과 충전 환경부터 확정", "주문 직후 지자체 보조금 접수 가능 여부 확인", "인도 전 보험·등록·결제와 차량 점검표 준비"],
    rows: [["예산", "차량가가 아니라 월 총지출", "할부금·보험·충전비까지 감당 가능"], ["보조금", "접수 주체와 잔여 물량", "출고 일정과 신청 기한이 맞음"], ["인도", "결제·보험·차량 상태", "서류와 앱 권한을 현장에서 확인"]],
    checklist: ["선수금과 월 상환 한도를 먼저 정한다", "집이나 직장의 충전 가능 시간을 확인한다", "거주지 공고의 신청 자격과 잔여 물량을 확인한다", "보험 견적은 차대번호가 나오기 전에 비교를 시작한다", "인도일 점검 항목과 문제 접수 방법을 메모한다"],
    relatedSlugs: ["tesla-buying-mistakes-checklist", "tesla-subsidy-apply-guide", "tesla-contract-cancel"],
    answerSlugs: ["model-y-worth-buying", "tesla-without-home-charger"],
    sourceKeys: ["teslaSupport", "teslaTestDrive", "evPortal"],
  },
  "tesla-buying-mistakes-checklist": {
    category: "구매 가이드",
    title: "테슬라 구매 전에 자주 놓치는 비용과 조건 7가지",
    description: "보조금 총액, 충전 환경, 보험료, 인도 일정처럼 계약 전에 확인하지 않으면 예산이 달라지는 항목을 사례별로 점검합니다.",
    question: "계약 버튼을 누르기 전에 어떤 실수를 가장 먼저 막아야 할까?",
    stage: "주문 직전",
    needLevel: "매우 높음",
    intent: "가격과 디자인은 정했지만 보조금·충전·보험·수리 같은 후속 비용을 빠뜨렸는지 확인하려는 사람",
    answer: "가장 흔한 실수는 표시 가격을 실제 지출로 받아들이는 것입니다. 보조금은 확정 금액이 아니며, 선수금과 금융 조건, 보험료, 충전 방식, 액세서리, 출고 시점에 따라 첫해 현금흐름이 달라집니다. 견적서의 월납입금이 낮아 보여도 긴 할부기간과 큰 선수금이 숨어 있을 수 있으므로 차량 인도일까지 필요한 현금과 이후 매달 나갈 돈을 별도로 계산해야 합니다. 충전기가 있다는 설명도 실제 귀가 시간에 사용할 수 있는지 확인하기 전에는 구매 조건으로 확정하지 않는 편이 안전합니다.",
    why: "구매 후 후회는 차량 성능보다 준비하지 않은 생활 조건에서 생기는 경우가 많습니다. 계약 전 체크리스트는 좋은 트림을 고르는 도구가 아니라, 내 환경과 맞지 않는 구매를 걸러내는 장치입니다. 특히 보조금이 줄거나 출고가 늦어지는 상황에서도 계약을 유지할 수 있는지 확인해야 판매 일정이 바뀌었을 때 성급한 결정을 피할 수 있습니다.",
    keyPoints: ["표시 가격과 실제 지출을 분리", "충전 가능 여부를 말이 아닌 시간표로 확인", "보험·타이어·수리 접근성까지 첫해 비용에 포함"],
    rows: [["보조금", "예상액을 확정액으로 봄", "공고·잔여 물량·출고일 교차 확인"], ["충전", "충전기가 있다는 사실만 확인", "야간 이용 가능성과 대기 시간 확인"], ["유지비", "전기료만 계산", "보험·타이어·주차·금융비용 포함"]],
    checklist: ["보조금을 제외한 가격도 감당 가능한지 계산한다", "평일 저녁 실제 충전기 점유 상태를 확인한다", "동일 운전자 조건으로 보험사별 견적을 받는다", "서비스센터와 공인 바디샵 이동 시간을 확인한다", "출고 지연과 보조금 소진이 겹칠 때의 대안을 정한다"],
    relatedSlugs: ["tesla-purchase-process-for-beginners", "tesla-affordability-salary-guide", "apartment-charging-checklist"],
    answerSlugs: ["tesla-without-home-charger", "tesla-repair-cost"],
    sourceKeys: ["teslaSupport", "evPortal", "fss"],
  },
  "model-y-trim-2026": {
    category: "모델·비교",
    title: "Model Y 트림 비교: 가격보다 먼저 볼 주행·공간·충전 조건",
    description: "RWD와 장거리·다인승 구성을 가격표만으로 고르지 않도록 주행 패턴, 탑승 인원, 충전 빈도, 월 예산으로 비교합니다.",
    question: "Model Y 트림은 어떤 사용 조건에서 차이가 크게 느껴질까?",
    stage: "모델과 트림 선택",
    needLevel: "매우 높음",
    intent: "상위 트림의 추가 비용이 실제 주행거리와 가족 사용성에 필요한지 판단하려는 사람",
    answer: "연간 주행거리가 짧고 집에서 자주 충전할 수 있다면 기본 트림의 경제성이 커집니다. 장거리 비중이 높거나 겨울철 여유 주행거리, 다인 탑승이 중요하면 배터리와 구동 방식, 좌석 구성을 먼저 비교해야 합니다.",
    why: "상위 트림은 숫자가 더 크다는 이유만으로 항상 유리하지 않습니다. 추가 가격을 지불한 기능을 실제 생활에서 얼마나 자주 쓰는지가 핵심입니다.",
    keyPoints: ["일상 주행거리와 충전 빈도로 배터리 여유 판단", "좌석 수보다 실제 탑승·적재 상황 확인", "추가 가격을 월 비용과 보유기간 총액으로 환산"],
    rows: [["도심 출퇴근", "주행거리 짧고 완속 충전 가능", "기본 트림부터 검토"], ["장거리 이동", "고속도로·겨울 주행 비중 높음", "여유 주행거리와 충전 횟수 비교"], ["가족 사용", "3열·적재공간 사용 빈도", "실차 탑승 후 좌석 구성 결정"]],
    checklist: ["일주일 중 가장 긴 이동 거리를 기준으로 잡는다", "겨울철과 고속도로 조건을 별도로 가정한다", "유모차와 짐을 싣고 실차 적재를 확인한다", "상위 트림 가격 차이를 월납입금으로 환산한다", "공식 주문 페이지의 최신 사양과 가격을 다시 확인한다"],
    relatedSlugs: ["model3-trim-comparison", "tesla-vs-ioniq5-ev6-2026", "tesla-affordability-salary-guide"],
    answerSlugs: ["model-y-real-range", "model-y-worth-buying"],
    sourceKeys: ["teslaModelY", "teslaSupport", "teslaRange"],
  },
  "model3-trim-comparison": {
    category: "모델·비교",
    title: "Model 3 트림 비교: 통근 거리와 성능 비용으로 고르는 방법",
    description: "RWD·장거리·고성능 트림을 통근 거리, 충전 여건, 승차감, 타이어 비용, 월 예산 기준으로 비교합니다.",
    question: "Model 3의 상위 트림 가격은 내 주행 조건에서 값을 할까?",
    stage: "모델과 트림 선택",
    needLevel: "높음",
    intent: "기본형의 효율과 상위 트림의 주행거리·성능 사이에서 예산을 배분하려는 사람",
    answer: "매일 충전할 수 있고 통근 거리가 일정하면 기본 트림만으로도 사용성이 충분할 수 있습니다. 상위 트림은 장거리 여유, 구동력, 성능을 자주 활용할 때 가치가 커지므로 가격 차이뿐 아니라 타이어와 보험 등 후속 비용도 함께 봐야 합니다.",
    why: "가속 성능은 시승에서 바로 느껴지지만 매달 부담하는 비용은 계약 뒤에 나타납니다. 자주 쓰는 기능과 드물게 쓰는 성능을 구분해야 과잉 선택을 막을 수 있습니다.",
    keyPoints: ["통근 거리와 충전 여건을 첫 기준으로 사용", "성능 트림의 타이어·보험 비용도 비교", "공식 사양은 계약 당일 다시 확인"],
    rows: [["RWD", "효율·초기 비용 우선", "통근과 일상 주행 중심"], ["장거리 구성", "주행 여유와 구동 안정성", "고속도로·겨울 이동이 잦음"], ["고성능 구성", "가속·제동·휠 사양", "성능 사용 목적이 분명함"]],
    checklist: ["평일과 주말의 최장 주행거리를 따로 기록한다", "집과 직장의 충전 가능 횟수를 확인한다", "휠 크기별 승차감과 타이어 가격을 비교한다", "보험 견적에서 트림별 차이를 확인한다", "시승은 같은 도로에서 후보 트림을 비교한다"],
    relatedSlugs: ["model-y-trim-2026", "tesla-vs-ioniq5-ev6-2026", "tesla-3year-cost"],
    answerSlugs: ["model-y-worth-buying", "tesla-tire-replacement"],
    sourceKeys: ["teslaModel3", "teslaSupport", "teslaRange"],
  },
  "tesla-vs-ioniq5-ev6-2026": {
    category: "모델·비교",
    title: "Model Y·아이오닉 5·EV6 비교: 충전과 서비스까지 보는 기준",
    description: "차량 가격과 제원 외에 실내 공간, 장거리 충전, 서비스 접근성, 보증, 중고 가치까지 구매 조건별로 비교합니다.",
    question: "세 차종의 차이를 실제 소유 조건에 맞춰 어떻게 비교해야 할까?",
    stage: "최종 후보 비교",
    needLevel: "매우 높음",
    intent: "수입 전기차의 소프트웨어·충전 경험과 국내 브랜드의 서비스·공간 장점을 함께 비교하려는 사람",
    answer: "한 항목의 우열보다 충전 경로와 서비스 접근성, 실내 활용, 운전자 보조 기능을 같은 조건에서 비교해야 합니다. 시승과 견적은 같은 주행거리·선수금·보유기간을 적용해야 가격표의 착시를 줄일 수 있습니다.",
    why: "전기차는 차량 자체뿐 아니라 충전망과 앱, 정비 네트워크를 함께 구매하는 성격이 강합니다. 거주지와 자주 가는 경로에 따라 같은 차의 만족도가 달라집니다.",
    keyPoints: ["동일한 금융·보유 조건으로 총비용 비교", "자주 쓰는 충전망과 서비스센터 거리 확인", "시승에서 공간·승차감·앱 사용성을 직접 점검"],
    rows: [["충전", "주요 이동 경로의 급속망", "우회와 대기 시간이 짧은가"], ["서비스", "센터·바디샵 접근성", "사고와 정비 때 대체 이동이 가능한가"], ["공간", "가족 탑승·적재 방식", "실제 짐을 싣고 불편이 없는가"]],
    checklist: ["후보 차량에 동일한 연간 주행거리를 적용한다", "집 주변과 장거리 경로의 충전소를 지도에 표시한다", "보험과 소모품 견적을 각각 받는다", "가족이 함께 시승해 승차감과 공간을 확인한다", "보증 조건과 서비스 예약 방법을 공식 문서로 확인한다"],
    relatedSlugs: ["model-y-trim-2026", "model3-trim-comparison", "tesla-3year-cost"],
    answerSlugs: ["model-y-vs-ioniq5", "model-y-vs-ev6"],
    sourceKeys: ["teslaModelY", "evPortal", "teslaWarranty"],
  },
  "new-vs-used-tesla-2026": {
    category: "구매 가이드",
    title: "신차와 중고 테슬라 비교: 가격 차보다 먼저 볼 비용",
    description: "보조금, 보증 잔여기간, 타이어·배터리 상태, 금융 금리, 소유권 이전 비용을 합쳐 신차와 중고차를 비교합니다.",
    question: "중고차가 싸 보일 때 실제로도 신차보다 유리한지 어떻게 확인할까?",
    stage: "신차·중고차 선택",
    needLevel: "높음",
    intent: "매물 가격 차이가 작거나 큰 상황에서 보증과 초기 정비비까지 반영한 실비용을 알고 싶은 사람",
    answer: "매물 가격만 빼서 비교하면 부족합니다. 신차 보조금과 금융 조건, 중고차의 보증 잔여기간·타이어·사고 이력·명의 이전 비용을 합산한 첫 3년 지출을 비교해야 합니다.",
    why: "중고차는 즉시 인도와 낮은 표시 가격이 장점이지만 상태 확인 책임이 구매자에게 더 큽니다. 가격 차이가 작다면 신차의 보증과 정책 혜택이 차이를 상쇄할 수 있습니다.",
    keyPoints: ["표시 가격 대신 3년 지출로 비교", "보증 잔여기간과 사고·정비 이력 확인", "신차 보조금과 중고 금융 금리를 함께 반영"],
    rows: [["신차", "보조금·전체 보증·최신 사양", "출고 대기와 초기 가격 감수"], ["중고", "즉시 인도·낮은 가격 가능", "상태 확인과 잔여 보증 중요"], ["공통", "보험·타이어·충전 준비", "동일 조건으로 총비용 계산"]],
    checklist: ["차대번호로 리콜과 정비 이력을 확인한다", "배터리·구동장치와 기본 보증의 잔여기간을 계산한다", "타이어 네 짝과 휠 손상 비용을 견적에 넣는다", "신차 보조금 적용 후 가격과 비교한다", "중고차 금융 금리와 현금 구매의 기회비용을 비교한다"],
    relatedSlugs: ["used-tesla-price-2026", "ev-battery-warranty-insurance-guide", "tesla-3year-cost"],
    answerSlugs: ["used-model-y-checklist", "tesla-battery-warranty"],
    sourceKeys: ["car365", "teslaWarranty", "evPortal"],
  },
  "used-tesla-price-2026": {
    category: "구매 가이드",
    title: "중고 테슬라 적정가를 판단하는 차량 상태 점검표",
    description: "연식과 주행거리뿐 아니라 보증 잔여기간, 사고·수리 이력, 타이어, 충전 부품, 소프트웨어 옵션으로 매물 가격을 판단합니다.",
    question: "같은 연식의 매물 가격이 다를 때 어떤 항목으로 차이를 설명할 수 있을까?",
    stage: "중고 매물 검토",
    needLevel: "매우 높음",
    intent: "시세보다 싸거나 비싼 매물의 이유를 확인하고 예상 정비비를 가격 협상에 반영하려는 사람",
    answer: "연식·주행거리·트림을 맞춘 뒤 사고 이력, 보증 잔여기간, 타이어와 휠, 충전 장비, 유료 소프트웨어의 귀속 여부를 차례로 확인해야 합니다. 상태를 금액으로 환산하지 못하면 싼 매물이 수리 후 더 비싸질 수 있습니다.",
    why: "전기차는 엔진 상태 대신 배터리·구동계 보증과 충전 이력, 전장 기능 확인이 중요합니다. 다만 화면에 표시된 주행 가능 거리 하나만으로 배터리 상태를 단정해서는 안 됩니다.",
    keyPoints: ["동일 트림·연식·주행거리끼리 시세 비교", "보증과 소모품 교체 예정 비용 반영", "소프트웨어 옵션의 차량 귀속 여부 확인"],
    rows: [["이력", "사고·침수·소유자 변경", "공식 이력과 실차 상태가 일치"], ["보증", "기본·배터리 보증 잔여", "예상 보유기간을 충분히 덮음"], ["소모품", "타이어·휠·필터·충전 장비", "교체비를 매물가에 더해 비교"]],
    checklist: ["자동차365와 보험 이력 정보를 교차 확인한다", "차대번호 기준 보증 종료일과 주행거리 한도를 적는다", "완속·급속 충전과 충전 포트 작동을 확인한다", "타이어 제조일과 편마모를 네 바퀴 모두 본다", "옵션 화면과 판매 설명이 일치하는지 계약서에 남긴다"],
    relatedSlugs: ["new-vs-used-tesla-2026", "ev-battery-warranty-insurance-guide", "tesla-contract-cancel"],
    answerSlugs: ["used-model-y-checklist", "tesla-battery-degradation"],
    sourceKeys: ["car365", "teslaWarranty", "teslaSupport"],
  },
  "tesla-affordability-salary-guide": {
    category: "구매·금융",
    title: "테슬라 구매 예산: 월급보다 월 잉여자금으로 계산하는 방법",
    description: "연봉 구간의 단순 추천 대신 선수금·할부금·보험·충전비·주차비를 반영해 감당 가능한 월 차량비를 계산합니다.",
    question: "내 소득에서 테슬라 월 지출을 어느 수준까지 허용해도 될까?",
    stage: "예산 한도 설정",
    needLevel: "매우 높음",
    intent: "월급만으로 구매 가능 여부를 판단하지 않고 생활비와 비상자금을 보존한 예산을 만들려는 사람",
    answer: "연봉보다 세후 월수입에서 고정생활비·대출상환·저축·비상예비비를 뺀 잉여자금이 기준입니다. 차량비에는 할부금뿐 아니라 보험, 충전, 주차, 세금, 타이어 적립액을 모두 넣어야 합니다.",
    why: "같은 월급이라도 주거비와 기존 부채, 가족 지출이 다르면 감당 가능한 차량비가 크게 달라집니다. 차량 구매 뒤 저축이 멈추거나 비상자금을 쓰게 된다면 예산이 과한 신호입니다.",
    keyPoints: ["연봉이 아닌 세후 잉여자금으로 판단", "월납입금 외 반복 비용과 교체비 적립 포함", "비상자금과 저축을 먼저 보존"],
    rows: [["필수지출", "주거·생활·기존 대출", "차량 구매 뒤에도 변동 없이 지불"], ["차량지출", "할부·보험·충전·주차", "월 잉여자금 안에서 감당"], ["안전망", "저축·비상예비비", "차량 때문에 중단하지 않음"]],
    checklist: ["최근 3개월 세후 수입의 평균을 구한다", "고정지출과 비정기 지출을 월평균으로 바꾼다", "보험료와 타이어 비용을 월 적립액으로 계산한다", "금리가 1%포인트 오르는 경우도 시험한다", "구매 뒤에도 유지할 저축액을 먼저 빼놓는다"],
    relatedSlugs: ["tesla-monthly-payment-guide", "ev-auto-loan-guide-2026", "tesla-3year-cost"],
    answerSlugs: ["tesla-insurance-cost", "tesla-car-tax"],
    sourceKeys: ["fss", "teslaModel3", "teslaModelY"],
  },
  "ev-auto-loan-guide-2026": {
    category: "구매·금융",
    title: "전기차 할부와 자동차대출 비교: 금리 외에 볼 조건",
    description: "금리·기간·중도상환수수료·근저당·부대비용·월 상환액을 같은 조건으로 맞춰 자동차 금융을 비교합니다.",
    question: "낮은 금리 상품이 실제 총비용도 가장 낮은지 어떻게 확인할까?",
    stage: "금융 상품 선택",
    needLevel: "매우 높음",
    intent: "카드 할부, 캐피탈, 은행 자동차대출 중 월 부담과 조기상환 조건을 비교하려는 사람",
    answer: "동일한 대출원금과 기간으로 월 상환액·총이자·중도상환수수료·부대비용을 비교해야 합니다. 월 납입금만 낮추려고 기간을 늘리면 총이자가 커질 수 있으므로 예상 보유기간과 조기상환 계획까지 넣어야 합니다.",
    why: "차량 가격 할인과 금융 조건이 묶인 상품은 표면 금리만으로 비교하기 어렵습니다. 승인 가능성과 신용점수 영향도 개인별로 달라 최종 계약서를 기준으로 판단해야 합니다.",
    keyPoints: ["동일 원금·기간으로 총비용 비교", "중도상환 계획과 수수료 확인", "할인 조건과 금융 비용을 분리"],
    rows: [["금리", "고정·변동과 적용 기준", "실제 승인 금리 확인"], ["기간", "월납입과 총이자", "보유기간보다 과도하게 길지 않음"], ["상환", "중도상환수수료·근저당", "조기 매각 때 비용 예측 가능"]],
    checklist: ["대출 원금과 기간을 모든 견적에서 같게 맞춘다", "취급수수료와 근저당 설정·해지 비용을 확인한다", "12개월·24개월 뒤 조기상환 비용을 계산한다", "차량 할인과 금융 이자를 별도 줄로 적는다", "실제 승인 전에는 광고 최저금리를 확정값으로 보지 않는다"],
    relatedSlugs: ["tesla-monthly-payment-guide", "ev-lease-installment-cash", "tesla-affordability-salary-guide"],
    answerSlugs: [],
    sourceKeys: ["fss", "law", "teslaSupport"],
  },
  "tesla-monthly-payment-guide": {
    category: "구매·금융",
    title: "테슬라 월납입금 계산: 선수금·금리·기간의 차이",
    description: "차량가에서 보조금과 선수금을 빼고 금리·기간을 적용하는 계산 순서와 월납입금이 낮아 보이는 이유를 설명합니다.",
    question: "같은 차인데 견적마다 월납입금이 다른 이유는 무엇일까?",
    stage: "견적 비교",
    needLevel: "매우 높음",
    intent: "선수금과 할부기간을 바꿨을 때 월 부담과 총이자가 어떻게 달라지는지 이해하려는 사람",
    answer: "월납입금은 실제 대출원금, 금리, 상환기간으로 결정됩니다. 보조금이 확정되지 않았거나 선수금에 등록비를 섞으면 견적끼리 비교할 수 없으므로 각 항목을 분리하고 총이자까지 확인해야 합니다.",
    why: "기간을 늘리면 월납입금은 낮아지지만 차량을 팔 때 남은 대출잔액이 중고 시세보다 클 수 있습니다. 낮은 월납입금보다 현금흐름과 총비용의 균형이 중요합니다.",
    keyPoints: ["차량가·보조금·선수금·대출원금을 분리", "월납입금과 총이자를 함께 확인", "예상 매각 시점의 대출잔액 점검"],
    rows: [["선수금", "대출원금과 비상자금", "생활 안전자금을 침해하지 않음"], ["기간", "월납입과 총이자", "차량 보유 예상기간과 맞음"], ["금리", "승인 금리와 변동 가능성", "광고금리가 아닌 계약값 사용"]],
    checklist: ["보조금을 제외한 경우와 포함한 경우를 각각 계산한다", "등록·보험 비용은 선수금과 분리한다", "36·48·60개월의 총이자를 비교한다", "예상 매각 시점의 남은 원금을 확인한다", "중도상환수수료를 계약서에서 확인한다"],
    relatedSlugs: ["ev-auto-loan-guide-2026", "tesla-affordability-salary-guide", "tesla-3year-cost"],
    answerSlugs: [],
    sourceKeys: ["fss", "teslaModel3", "teslaModelY"],
  },
  "ev-lease-installment-cash": {
    category: "구매·금융",
    title: "전기차 현금·할부·리스 비교: 소유와 현금흐름의 차이",
    description: "초기 현금, 월 지출, 총비용, 중도 처분, 주행거리 제한, 세무 처리를 기준으로 구매 방식을 비교합니다.",
    question: "월 납입액이 비슷한 현금·할부·리스는 실제로 무엇이 다를까?",
    stage: "결제 방식 선택",
    needLevel: "높음",
    intent: "초기 자금을 아끼면서도 소유권과 중도 처분 조건을 놓치지 않으려는 개인·사업자",
    answer: "현금은 이자 없이 즉시 소유하지만 자금이 묶이고, 할부는 소유를 전제로 비용을 나눠 내며, 리스는 계약 종료 조건과 주행거리·반납 기준이 중요합니다. 월 납입액 대신 계약 전체 현금유출과 종료 시 남는 자산을 비교해야 합니다.",
    why: "리스의 세무상 유불리는 사업 형태와 사용 증빙에 따라 달라 일률적으로 단정할 수 없습니다. 개인 구매자는 반납 손상 비용과 중도해지 조건을 특히 확인해야 합니다.",
    keyPoints: ["계약 전체 현금유출과 종료 시 자산을 비교", "리스의 주행거리·반납·중도해지 조건 확인", "세무 효과는 사업 형태별로 별도 검토"],
    rows: [["현금", "초기 지출 큼·이자 없음", "비상자금이 충분함"], ["할부", "소유권·이자·상환기간", "월 현금흐름 관리가 필요"], ["리스", "반납·인수·주행거리 조건", "교체 주기와 계약조건이 맞음"]],
    checklist: ["모든 방식의 3년 또는 5년 총현금유출을 구한다", "계약 종료 시 차량 소유 여부를 표시한다", "리스 주행거리 한도와 초과 비용을 확인한다", "중도 매각·해지 때 부담할 금액을 비교한다", "사업자는 세무 전문가에게 실제 비용처리 가능 범위를 확인한다"],
    relatedSlugs: ["ev-auto-loan-guide-2026", "tesla-monthly-payment-guide", "tesla-3year-cost"],
    answerSlugs: [],
    sourceKeys: ["fss", "nts", "law"],
  },
  "tesla-3year-cost": {
    category: "총소유비용",
    title: "테슬라 3년 총소유비용 계산: 감가와 금융비용까지 보기",
    description: "차량가에서 끝내지 않고 감가상각·할부이자·보험·충전·세금·타이어를 합쳐 3년 소유비용을 계산합니다.",
    question: "전기료가 저렴하면 테슬라의 총소유비용도 항상 낮을까?",
    stage: "최종 예산 검증",
    needLevel: "매우 높음",
    intent: "내연기관차나 다른 전기차와 비교할 때 실제 보유기간 동안의 비용 차이를 알고 싶은 사람",
    answer: "충전비 절감만으로 총소유비용을 판단할 수 없습니다. 구매가격과 매각 예상가의 차이, 금융비용, 보험, 세금, 타이어, 충전비를 같은 보유기간과 주행거리로 합산해야 합니다.",
    why: "전기차는 정기 정비 항목이 적지만 차량 가격과 감가, 보험료가 절감액을 상쇄할 수 있습니다. 결과는 충전 방식과 중고 가치 가정에 민감하므로 한 숫자보다 여러 시나리오를 보는 것이 안전합니다.",
    keyPoints: ["구매가가 아닌 감가상각을 비용에 반영", "금융비용·보험·타이어까지 포함", "충전단가와 매각가를 바꾼 시나리오 비교"],
    rows: [["초기", "실구매가·등록·충전 준비", "보조금 확정 전후 구분"], ["보유", "이자·보험·충전·세금·소모품", "연간 주행거리와 일치"], ["매각", "예상 중고가", "낙관·기준·보수 시나리오 사용"]],
    checklist: ["실구매가와 예상 매각가를 별도 입력한다", "할부 이자와 중도상환 비용을 포함한다", "완속·급속 충전 비율을 실제 생활에 맞춘다", "보험과 타이어는 실제 견적을 사용한다", "매각가를 낮춘 보수적 시나리오도 확인한다"],
    relatedSlugs: ["tesla-affordability-salary-guide", "tesla-ev-maintenance-cost", "tesla-insurance-guide"],
    answerSlugs: ["tesla-insurance-cost", "tesla-tire-replacement"],
    sourceKeys: ["teslaSupport", "fss", "evPortal"],
  },
  "tesla-insurance-guide": {
    category: "유지비·세제",
    title: "테슬라 자동차보험 견적 비교: 보험료가 달라지는 조건",
    description: "운전자 범위·자기부담금·자차 담보·첨단안전장치·수리망을 같은 조건으로 맞춰 보험 견적을 비교합니다.",
    question: "보험사별 견적 차이를 보장 공백 없이 비교하려면 무엇을 맞춰야 할까?",
    stage: "계약 전·갱신 전",
    needLevel: "높음",
    intent: "가장 싼 보험료만 고르지 않고 사고 수리와 자기부담 위험까지 비교하려는 사람",
    answer: "운전자 범위, 연령, 주행거리 특약, 자차 가입금액, 자기부담금, 대물 한도를 같게 맞춘 뒤 보험료를 비교해야 합니다. 수리비가 큰 사고에 대비해 Tesla 공인 바디샵 이용과 부품 조달 과정도 확인할 필요가 있습니다.",
    why: "견적이 낮아도 담보 한도나 운전자 범위가 다르면 같은 상품이 아닙니다. 차량 인도 전 실제 차대번호와 운전자 조건으로 다시 산출해야 합니다.",
    keyPoints: ["담보와 운전자 조건을 동일하게 맞춤", "자차·자기부담금과 수리망을 함께 확인", "차대번호 발급 후 최종 견적 재확인"],
    rows: [["운전자", "범위·연령·경력", "실제 운전자 전원이 보장"], ["차량", "자차 가입금액·첨단장치", "수리 시 보장 공백 없음"], ["특약", "주행거리·안전장치·블랙박스", "실제 충족 가능한 조건만 선택"]],
    checklist: ["보험사마다 운전자와 담보 조건을 같게 입력한다", "대물 한도와 자차 자기부담금을 확인한다", "첨단안전장치 특약 적용 여부를 확인한다", "공인 바디샵과 렌트 특약의 범위를 확인한다", "인도일 전 보험 개시 시각을 차량 수령과 맞춘다"],
    relatedSlugs: ["tesla-3year-cost", "tesla-ev-maintenance-cost", "new-vs-used-tesla-2026"],
    answerSlugs: ["tesla-insurance-cost", "tesla-repair-cost"],
    sourceKeys: ["fss", "teslaSupport", "teslaWarranty"],
  },
  "tesla-ev-maintenance-cost": {
    category: "유지비·세제",
    title: "테슬라 유지비 항목: 충전·보험·타이어·점검 비용",
    description: "엔진오일이 없다는 설명을 넘어 매달·매년·주기적으로 발생하는 비용과 정비 항목을 구분해 계산합니다.",
    question: "테슬라는 정비 항목이 적다면 실제 유지비도 항상 저렴할까?",
    stage: "구매 전·보유 중",
    needLevel: "매우 높음",
    intent: "전기료 외에 보험·타이어·에어필터·브레이크액·수리비 적립까지 포함한 유지비를 알고 싶은 사람",
    answer: "정기 교환 항목은 내연기관차보다 적지만 보험과 타이어, 충전 방식, 주차비에 따라 총유지비는 달라집니다. 월 반복비와 몇 년마다 발생하는 교체비를 나눠 적립해야 예산이 흔들리지 않습니다.",
    why: "회생제동으로 브레이크 사용이 줄어도 차량 무게와 순간 토크는 타이어 마모에 영향을 줄 수 있습니다. 정비 주기는 차량 상태와 운행 환경을 기준으로 공식 안내를 확인해야 합니다.",
    keyPoints: ["월 반복비와 주기 교체비를 분리", "타이어와 보험을 충전비만큼 중요하게 반영", "차량 상태 기반 점검과 공식 서비스 안내 확인"],
    rows: [["매월", "충전·주차·세차", "실제 사용량 기반"], ["매년", "보험·자동차세·필터", "견적과 교체 이력 반영"], ["주기", "타이어·브레이크액·수리", "월 적립액으로 준비"]],
    checklist: ["완속과 급속 충전 비율을 기록한다", "보험료와 자동차세를 12개월로 나눈다", "타이어 교체 예상 주기와 가격을 적립한다", "서비스센터 이동과 대차 비용도 고려한다", "차량 앱과 공식 지원의 점검 권고를 확인한다"],
    relatedSlugs: ["tesla-3year-cost", "tesla-insurance-guide", "ev-battery-warranty-insurance-guide"],
    answerSlugs: ["tesla-maintenance-items", "tesla-tire-replacement"],
    sourceKeys: ["teslaSupport", "teslaWarranty", "fss"],
  },
  "tesla-subsidy-apply-guide": {
    category: "보조금",
    title: "테슬라 전기차 보조금 신청 순서와 담당 주체",
    description: "구매자·판매사·지자체가 각각 처리하는 단계와 신청 자격, 잔여 물량, 출고·등록 기한을 순서대로 설명합니다.",
    question: "차량을 주문하면 보조금은 자동으로 확보되는 것일까?",
    stage: "주문 전후",
    needLevel: "매우 높음",
    intent: "누가 신청서를 제출하고 어느 시점에 보조금이 확정되는지 알고 싶은 개인 구매자",
    answer: "온라인 주문만으로 보조금이 확보되지는 않습니다. 거주지 공고의 자격과 잔여 물량을 확인하고, 판매사와 신청 서류·출고 가능 시점을 맞춘 뒤 지자체의 대상자 선정 절차를 거쳐야 합니다.",
    why: "신청 방식과 기한은 지자체 공고에 따라 달라질 수 있으며 예산이 소진되면 같은 차량도 지원받지 못할 수 있습니다. 주문·신청·출고·등록을 하나의 일정표로 관리해야 합니다.",
    keyPoints: ["주문과 보조금 선정은 별도 절차", "거주지·차량·출고 기한을 동시에 확인", "판매사와 지자체의 담당 단계를 구분"],
    rows: [["구매자", "자격·주소·서류 확인", "공고 기준을 충족"], ["판매사", "지원 신청·차량 출고 협의", "기한 안에 처리 가능"], ["지자체", "대상자 선정·지급", "잔여 예산과 절차 확인"]],
    checklist: ["거주지 지자체의 최신 공고 원문을 연다", "차량이 지원 대상 목록에 있는지 확인한다", "판매 담당자에게 접수 주체와 예정일을 묻는다", "대상자 선정과 출고·등록 기한을 달력에 적는다", "변경사항은 통화 내용보다 공고와 서면 안내로 남긴다"],
    relatedSlugs: ["tesla-subsidy-required-docs", "subsidy-budget-timing-strategy", "how-to-read-local-subsidy-notice"],
    answerSlugs: [],
    sourceKeys: ["evPortal", "environment", "teslaSupport"],
  },
  "tesla-subsidy-required-docs": {
    category: "보조금",
    title: "전기차 보조금 신청 서류: 개인·법인·추가지원 체크리스트",
    description: "공통 서류와 거주·사업자·가족관계·추가지원 증빙을 구분하고 발급일과 제출 형식을 확인하는 방법을 정리합니다.",
    question: "보조금 서류를 한 번에 통과하려면 무엇을 미리 준비해야 할까?",
    stage: "보조금 접수 전",
    needLevel: "매우 높음",
    intent: "개인·법인·추가 지원 자격에 맞는 증빙을 빠뜨리지 않고 준비하려는 구매자",
    answer: "공통 신청서 외에 주소, 사업자 상태, 가족관계, 추가 지원 자격을 증명하는 서류가 달라질 수 있습니다. 지자체 공고의 서식 번호와 발급 기준일, 주민등록번호 표시 범위를 확인하고 판매사에 제출 형식을 다시 확인해야 합니다.",
    why: "서류 이름이 같아도 발급일이나 주소 변동 이력, 원본·사본 요구가 다르면 보완 요청을 받을 수 있습니다. 출고 기한이 촉박할수록 작은 보완도 일정에 영향을 줍니다.",
    keyPoints: ["공통·개인·법인·추가지원 서류를 분리", "발급일·주소·표시 범위를 공고와 대조", "제출 전 파일명과 서명 누락 확인"],
    rows: [["공통", "신청서·동의서·차량 계약", "최신 공고 서식 사용"], ["자격", "주소·사업자·가족관계", "신청일 기준 조건 충족"], ["추가지원", "청년·다자녀·취약계층 증빙", "중복 가능 여부 확인"]],
    checklist: ["공고 첨부파일의 서식 목록을 먼저 출력한다", "모든 증명서의 발급일과 주소를 확인한다", "서명·날인·개인정보 표시 범위를 점검한다", "스캔 파일은 문서별로 이름을 명확히 붙인다", "제출 뒤 접수번호와 보완 연락 채널을 기록한다"],
    relatedSlugs: ["tesla-subsidy-apply-guide", "how-to-read-local-subsidy-notice", "subsidy-refund-ownership-period-guide"],
    answerSlugs: [],
    sourceKeys: ["evPortal", "environment", "law"],
  },
  "subsidy-remaining-check": {
    category: "보조금",
    title: "전기차 보조금 잔여 물량 확인과 출고 일정 맞추기",
    description: "잔여 대수 화면을 해석하는 법과 접수 대기·대상자 선정·출고 가능일을 함께 확인해야 하는 이유를 설명합니다.",
    question: "잔여 물량이 표시되어 있으면 내 보조금도 확정된 것일까?",
    stage: "주문 전·출고 전",
    needLevel: "매우 높음",
    intent: "지자체 예산이 남아 있는지 확인하고 차량 출고와 접수 시점을 맞추려는 구매자",
    answer: "잔여 물량은 확인 시점의 공개 현황일 뿐 개인의 지원 확정을 뜻하지 않습니다. 접수 대기 건수와 지자체 처리 속도, 대상자 선정 여부, 차량 출고 가능일을 판매사와 지자체 양쪽에서 확인해야 합니다.",
    why: "화면 갱신과 실제 접수 사이에 시차가 있을 수 있고, 취소분이나 추가 예산이 반영되기도 합니다. 한 번의 조회 결과보다 확인 날짜와 담당자 답변을 기록하는 것이 중요합니다.",
    keyPoints: ["잔여 물량과 개인 선정 여부를 구분", "접수 대기·처리 속도·출고일을 함께 확인", "조회 날짜와 담당 부서 답변을 기록"],
    rows: [["공개 현황", "잔여 대수·접수 건수", "조회 시각을 함께 저장"], ["개인 상태", "접수·보완·선정 여부", "접수번호로 확인"], ["차량", "배정·출고·등록 가능일", "공고 기한 안에 완료 가능"]],
    checklist: ["무공해차 통합누리집과 지자체 공고를 함께 본다", "잔여 물량 화면의 조회 날짜를 저장한다", "판매사에 차량 배정과 접수 예정일을 묻는다", "지자체 담당 부서에 대기 건수와 처리 기간을 확인한다", "보조금 없이 구매할 경우의 예산도 준비한다"],
    relatedSlugs: ["subsidy-budget-timing-strategy", "tesla-subsidy-apply-guide", "how-to-read-local-subsidy-notice"],
    answerSlugs: [],
    sourceKeys: ["evPortal", "environment", "teslaSupport"],
  },
  "subsidy-budget-timing-strategy": {
    category: "보조금",
    title: "전기차 보조금 예산 소진에 대비한 주문 시점과 대안",
    description: "연초·연말이라는 단순 구분 대신 공고일, 접수 순서, 출고 가능일, 추가경정 예산, 취소분을 확인해 일정을 세웁니다.",
    question: "보조금 소진 위험을 줄이려면 언제 무엇을 확인해야 할까?",
    stage: "구매 시점 결정",
    needLevel: "높음",
    intent: "보조금을 받기 위해 주문을 서두를지 다음 공고를 기다릴지 판단하려는 사람",
    answer: "연초라고 항상 여유가 있고 연말이라고 항상 불가능한 것은 아닙니다. 지자체 공고일과 접수 기준, 차량 출고 가능일, 잔여 물량, 추가 예산 가능성을 확인한 뒤 보조금이 없을 때의 구매 가능 여부도 함께 정해야 합니다.",
    why: "차량 주문과 보조금 접수 사이의 간격이 길면 예산이 남아 있어도 기한을 놓칠 수 있습니다. 반대로 취소분이나 추가 공고가 생길 수 있으므로 확인 채널을 정해두는 편이 좋습니다.",
    keyPoints: ["계절보다 지자체 공고와 출고 가능일을 기준으로 판단", "보조금 미확보 시 대체 예산 설정", "취소분·추가 공고를 확인할 채널 마련"],
    rows: [["공고", "접수 시작·선정 기준", "내 자격과 순서가 명확"], ["차량", "예상 배정·출고일", "등록 기한을 지킬 수 있음"], ["대안", "무보조 구매·다음 공고", "예산과 필요 시점에 맞음"]],
    checklist: ["지자체 공고 알림과 무공해차 포털을 정기 확인한다", "판매사에서 차량 배정 가능일을 서면으로 확인한다", "대상자 선정 방식이 접수순인지 출고순인지 읽는다", "보조금 없이 살 수 있는 최대 가격을 정한다", "취소분과 추가 공고 문의 시점을 달력에 넣는다"],
    relatedSlugs: ["subsidy-remaining-check", "tesla-purchase-process-for-beginners", "tesla-subsidy-apply-guide"],
    answerSlugs: [],
    sourceKeys: ["evPortal", "environment", "teslaSupport"],
  },
  "subsidy-refund-ownership-period-guide": {
    category: "보조금",
    title: "전기차 보조금 의무운행기간과 환수 조건 확인법",
    description: "매각·폐차·이전 등록·수출 등 상황별로 의무운행기간과 보조금 환수 가능성을 공고와 지자체에 확인하는 방법을 정리합니다.",
    question: "보조금을 받은 차를 예상보다 빨리 팔면 어떤 절차가 필요할까?",
    stage: "구매 전·매각 전",
    needLevel: "높음",
    intent: "이사·해외 체류·차량 교체 가능성이 있어 의무 보유와 환수 위험을 미리 알고 싶은 사람",
    answer: "의무운행기간과 환수율은 적용 공고와 처분 사유에 따라 확인해야 합니다. 차량을 팔거나 이전 등록하기 전에 최초 지원 지자체에 신고·승인 필요 여부와 환수 금액 산정 기준을 문의해야 합니다. 중고차 매매 계약서에는 보조금 관련 절차를 누가 언제 완료할지도 적어 등록 지연과 비용 분쟁을 줄이는 것이 좋습니다.",
    why: "중고차 거래가 완료된 뒤 조건을 확인하면 매도자와 매수자 모두 등록 일정에 문제가 생길 수 있습니다. 예외 사유가 있더라도 증빙과 사전 절차가 필요할 수 있습니다. 지자체를 옮겨 등록하거나 가족에게 명의를 이전하는 경우도 단순 매각과 같은 절차로 처리된다고 가정하지 말고, 지원금을 지급한 지자체에 처분 유형을 정확히 설명해야 합니다.",
    keyPoints: ["최초 지원 공고의 의무운행 조건 확인", "매각·이전 전에 지자체 담당 부서 문의", "환수 산식과 예외 증빙을 서면으로 확보"],
    rows: [["매각", "명의 이전·지역 이전", "사전 승인·신고 여부 확인"], ["폐차", "사고·천재지변·노후", "예외 사유와 증빙 확인"], ["환수", "보유기간·처분 사유", "공고의 산정표로 계산"]],
    checklist: ["차량 구매 당시 적용된 공고를 찾는다", "지원금을 지급한 지자체 담당 부서를 확인한다", "매매 계약 전에 신고·승인 순서를 문의한다", "환수 예상액과 납부 시점을 서면으로 받는다", "매수자에게 보조금 관련 제한을 계약 전에 알린다"],
    relatedSlugs: ["tesla-subsidy-apply-guide", "tesla-contract-cancel", "new-vs-used-tesla-2026"],
    answerSlugs: [],
    sourceKeys: ["evPortal", "environment", "law"],
  },
  "subsidy-vs-tax-deduction": {
    category: "유지비·세제",
    title: "전기차 보조금과 세금 감면: 실구매가에 반영하는 순서",
    description: "구매보조금과 개별소비세·취득세 등 세금 항목을 구분하고 견적서에서 중복 계산하지 않는 방법을 설명합니다.",
    question: "보조금과 세금 혜택은 모두 차량 가격에서 한 번씩 빼면 될까?",
    stage: "견적 검증",
    needLevel: "높음",
    intent: "광고 문구의 최대 혜택이 실제 견적에 어떻게 반영되는지 확인하려는 개인·사업자",
    answer: "보조금과 세금 감면은 적용 근거와 시점이 다릅니다. 차량 가격에 이미 반영된 세금 혜택을 다시 빼지 말고, 주문 견적·등록 비용·보조금 지급 항목을 줄별로 구분해야 합니다.",
    why: "혜택을 모두 더한 최대 금액은 개인 자격과 차량 가격, 등록 시점에 따라 달라질 수 있습니다. 사업자의 비용처리와 부가가치세 문제는 개인 구매 혜택과 별도로 검토해야 합니다.",
    keyPoints: ["보조금과 세금 감면의 적용 단계 구분", "견적에 이미 반영된 혜택의 중복 차감 방지", "개인과 사업자의 세무 처리를 분리"],
    rows: [["차량 견적", "출고가와 포함 세금", "혜택 반영 여부 표시"], ["등록", "취득 관련 세금·공채", "등록지와 시점 기준 확인"], ["보조금", "국고·지방·추가지원", "선정 확정 금액만 반영"]],
    checklist: ["주문 견적에서 세전·세후 표시를 확인한다", "등록 대행 비용과 세금을 분리한다", "보조금은 예상액과 확정액을 따로 적는다", "혜택의 적용 종료일과 차량 등록일을 비교한다", "사업자는 비용처리와 세액 문제를 세무 전문가에게 확인한다"],
    relatedSlugs: ["tesla-subsidy-apply-guide", "tesla-affordability-salary-guide", "tesla-3year-cost"],
    answerSlugs: ["tesla-car-tax"],
    sourceKeys: ["nts", "evPortal", "environment"],
  },
  "how-to-read-local-subsidy-notice": {
    category: "보조금",
    title: "지자체 전기차 보조금 공고문에서 먼저 읽을 항목",
    description: "지원 대상·거주 요건·선정 순서·출고 기한·추가지원·의무운행·제출 서식을 빠르게 찾는 읽기 순서를 안내합니다.",
    question: "긴 공고문에서 내 구매 가능성을 판단하려면 어디부터 읽어야 할까?",
    stage: "보조금 조사 시작",
    needLevel: "매우 높음",
    intent: "요약글이 아니라 자기 거주지의 원문에서 자격과 일정, 예외 조건을 확인하려는 사람",
    answer: "총 지원금보다 지원 대상과 거주 요건, 선정 방식, 출고·등록 기한을 먼저 봐야 합니다. 그다음 차량별 금액, 추가 지원, 의무운행, 제출 서식을 확인하면 내 구매 일정에 적용할 수 있습니다.",
    why: "공고 제목이 같아도 지자체마다 접수 순서와 거주 요건, 추가 지원이 다를 수 있습니다. 요약 화면은 출발점이고 최종 판단은 공고 원문과 담당 부서 확인을 기준으로 해야 합니다.",
    keyPoints: ["금액보다 자격·선정 방식·기한을 먼저 확인", "본문과 첨부 서식을 함께 읽음", "모호한 조건은 담당 부서에 서면 확인"],
    rows: [["자격", "거주·연령·사업자 조건", "신청 기준일에 충족"], ["일정", "접수·선정·출고·등록", "차량 배정 일정과 맞음"], ["의무", "보유·이전·환수 조건", "향후 매각 계획과 충돌 없음"]],
    checklist: ["공고일과 수정 공고 여부를 확인한다", "지원 대상과 제외 대상 문장을 먼저 표시한다", "선정 순서와 출고·등록 기한을 달력에 옮긴다", "차량별 지원금 표에서 정확한 트림을 찾는다", "필요 서식과 문의 담당 부서를 마지막에 정리한다"],
    relatedSlugs: ["tesla-subsidy-apply-guide", "tesla-subsidy-required-docs", "subsidy-remaining-check"],
    answerSlugs: [],
    sourceKeys: ["evPortal", "environment", "law"],
  },
  "apartment-charging-checklist": {
    category: "충전",
    title: "아파트에서 테슬라를 사기 전 확인할 충전 조건",
    description: "충전기 설치 유무가 아니라 야간 점유, 요금, 주차 규정, 고장 대응, 대체 충전소까지 실제 이용 가능성을 확인합니다.",
    question: "아파트에 충전기가 있다는 사실만으로 구매 준비가 끝난 것일까?",
    stage: "차량 계약 전",
    needLevel: "매우 높음",
    intent: "공동주택에서 매일 충전 가능한지, 충전 경쟁과 주차 규정이 생활에 미칠 영향을 알고 싶은 사람",
    answer: "충전기 대수보다 내가 귀가하는 시간의 점유율과 주차 규정이 중요합니다. 운영사업자, 요금, 최대 주차시간, 고장 신고, 신규 설치 계획을 관리사무소와 실제 사용자에게 확인해야 합니다.",
    why: "자택 충전이 불안정하면 급속충전 의존도가 높아져 시간과 비용이 늘어납니다. 계약 전에 일주일 생활 동선으로 충전 가능성을 시험해야 합니다.",
    keyPoints: ["충전기 수보다 이용 시간대의 점유율 확인", "요금·주차 제한·고장 대응 절차 점검", "인근 대체 충전소를 두 곳 이상 확보"],
    rows: [["이용성", "귀가 시간 점유·대기", "주 2~3회 안정적으로 이용"], ["규정", "주차 제한·완료 후 이동", "생활 시간과 충돌 없음"], ["대체", "인근 완속·급속 충전소", "고장·혼잡 때 우회 가능"]],
    checklist: ["평일 저녁과 주말에 충전 구역을 직접 본다", "관리사무소에 운영사업자와 요금을 묻는다", "충전 완료 후 이동 규정과 민원 절차를 확인한다", "앱 가입과 결제 방법을 미리 시험한다", "집 주변 대체 충전소의 운영시간을 확인한다"],
    relatedSlugs: ["home-charger-guide", "ev-public-charger-network", "tesla-supercharger-charging-guide"],
    answerSlugs: ["tesla-without-home-charger", "ev-charging-card"],
    sourceKeys: ["teslaSupport", "evPortal", "environment"],
  },
  "home-charger-guide": {
    category: "충전",
    title: "전기차 홈 충전기 설치 전 확인할 전력·비용·승인 절차",
    description: "단독주택과 공동주택에서 전력 용량, 배선 거리, 주차면 권한, 사업자 견적, 요금제를 확인하는 순서를 설명합니다.",
    question: "충전기 본체 가격 외에 어떤 조건이 설치비와 사용성을 바꿀까?",
    stage: "차량 계약 전·설치 전",
    needLevel: "높음",
    intent: "집에서 안정적으로 충전하기 위해 실제 설치 가능성과 회수기간을 판단하려는 사람",
    answer: "분전반 여유 용량과 주차면까지의 배선 거리, 벽 타공과 방수, 주차 권한, 관리주체 승인이 설치 가능성과 비용을 결정합니다. 최소 두 곳의 현장 견적을 받아 공사 범위와 사후 서비스를 비교해야 합니다.",
    why: "충전기 가격만 보고 계약하면 추가 배선과 전력 증설 비용이 뒤늦게 붙을 수 있습니다. 월 절감액은 기존 급속충전 비율과 실제 주행거리를 기준으로 계산해야 합니다.",
    keyPoints: ["전력 용량·배선 거리·주차 권한을 먼저 확인", "본체와 공사·증설·통신 비용을 분리", "급속 대비 절감액으로 회수기간 계산"],
    rows: [["현장", "분전반·배선·방수·주차면", "안전 기준과 사용 권한 충족"], ["견적", "본체·공사·증설·통신", "추가 비용 범위가 명확"], ["운영", "요금·앱·A/S", "장기 사용과 고장 대응 가능"]],
    checklist: ["전기 전문가에게 분전반 여유 용량을 확인받는다", "주차면 소유·사용 권한과 관리 규정을 확인한다", "두 개 이상 업체에서 현장 견적을 받는다", "공사비와 전력 증설 비용을 분리해 비교한다", "고장 접수와 보증 기간을 계약서에 남긴다"],
    relatedSlugs: ["apartment-charging-checklist", "ev-public-charger-network", "tesla-3year-cost"],
    answerSlugs: ["tesla-without-home-charger"],
    sourceKeys: ["teslaSupport", "evPortal", "environment"],
  },
  "tesla-supercharger-charging-guide": {
    category: "충전",
    title: "테슬라 수퍼차저 이용법과 충전 시간을 줄이는 방법",
    description: "경로 계획, 배터리 예열, 충전량에 따른 속도, 결제, 혼잡 수수료, 충전 종료 후 이동까지 실제 이용 순서를 정리합니다.",
    question: "수퍼차저에서 오래 기다리지 않고 필요한 만큼 충전하려면 어떻게 해야 할까?",
    stage: "첫 장거리 전·보유 중",
    needLevel: "높음",
    intent: "급속충전 속도와 결제, 혼잡 정책을 이해하고 장거리 정차 시간을 줄이려는 사람",
    answer: "차량 내비게이션으로 수퍼차저를 목적지로 설정해 배터리 예열을 유도하고, 도착 배터리 잔량을 낮게 계획하면 충전 초반의 높은 속도를 활용하기 쉽습니다. 높은 충전량에서는 속도가 떨어지므로 다음 구간에 필요한 수준까지만 충전하는 편이 효율적입니다.",
    why: "표시된 최대 출력은 항상 유지되는 값이 아니며 배터리 온도·잔량·충전기 혼잡에 따라 달라집니다. 요금과 혼잡 수수료는 현장과 앱에서 최신 조건을 확인해야 합니다.",
    keyPoints: ["차량 내비게이션으로 경로와 배터리 예열 준비", "높은 충전량 구간의 속도 저하 고려", "앱 결제와 혼잡·점거 조건을 현장에서 확인"],
    rows: [["도착 전", "경로 설정·예상 잔량", "충전소까지 안전 여유 확보"], ["충전 중", "출력·목표 충전량", "다음 구간에 필요한 만큼 충전"], ["종료", "결제·점거·혼잡 수수료", "완료 후 정해진 시간 안에 이동"]],
    checklist: ["출발 전에 Tesla 앱의 결제 수단을 확인한다", "차량 내비게이션에서 수퍼차저를 목적지로 설정한다", "다음 충전소와 우회 충전소를 함께 확인한다", "현장 안내의 요금과 혼잡 조건을 읽는다", "충전 종료 알림을 받으면 차량을 바로 이동한다"],
    relatedSlugs: ["ev-public-charger-network", "apartment-charging-checklist", "home-charger-guide"],
    answerSlugs: ["tesla-fast-charging-ccs", "tesla-seoul-to-busan"],
    sourceKeys: ["teslaCharging", "teslaRange", "teslaSupport"],
  },
  "ev-public-charger-network": {
    category: "충전",
    title: "공공 급속충전 이용 전 확인할 카드·커넥터·요금",
    description: "충전사업자, 회원·비회원 요금, 로밍, 커넥터 호환, 주차비, 고장 신고를 기준으로 공공 충전망을 준비합니다.",
    question: "충전카드 한 장으로 모든 급속충전기를 같은 요금에 쓸 수 있을까?",
    stage: "차량 인도 전",
    needLevel: "높음",
    intent: "수퍼차저 외 공공·민간 충전기를 사용하고 요금과 결제 실패를 줄이려는 사람",
    answer: "사업자와 로밍 관계에 따라 회원·비회원 요금과 결제 방식이 달라질 수 있습니다. 차량의 커넥터와 어댑터 호환, 충전기 출력, 주차비, 운영시간을 충전소별로 확인해야 합니다.",
    why: "지도에 표시된 충전기가 항상 사용 가능한 것은 아니며 고장·점검·주차장 폐쇄가 있을 수 있습니다. 자주 가는 경로는 주 충전소와 대체 충전소를 한 쌍으로 준비하는 것이 좋습니다.",
    keyPoints: ["사업자별 회원·로밍·비회원 요금 구분", "차량·어댑터·커넥터 호환 확인", "주차비와 운영시간까지 총 충전비에 포함"],
    rows: [["결제", "회원카드·앱·신용카드", "주 결제와 예비 결제 준비"], ["호환", "커넥터·어댑터·출력", "차량에서 실제 사용 가능"], ["현장", "주차비·운영시간·고장", "총비용과 우회 가능성 확인"]],
    checklist: ["자주 쓰는 사업자 앱과 카드를 미리 등록한다", "차량과 어댑터의 지원 규격을 확인한다", "첫 이용 전에 소액 충전을 시험한다", "주차비와 충전 완료 후 이동 규정을 확인한다", "장거리 경로마다 대체 충전소를 저장한다"],
    relatedSlugs: ["tesla-supercharger-charging-guide", "apartment-charging-checklist", "home-charger-guide"],
    answerSlugs: ["ev-charging-card", "tesla-fast-charging-ccs"],
    sourceKeys: ["evPortal", "teslaSupport", "teslaCharging"],
  },
  "ev-battery-warranty-insurance-guide": {
    category: "소유·관리",
    title: "테슬라 배터리·구동장치 보증과 보험의 역할 구분",
    description: "제조 결함 보증과 사고 보험이 각각 무엇을 다루는지, 트림별 기간·주행거리·용량 유지 조건을 확인하는 방법을 설명합니다.",
    question: "배터리 문제가 생기면 제조사 보증과 자동차보험 중 어디에 요청해야 할까?",
    stage: "구매 전·고장 발생 시",
    needLevel: "매우 높음",
    intent: "고가 배터리의 고장·사고·침수·자연 열화가 어떤 제도로 보장되는지 알고 싶은 사람",
    answer: "제조상 결함과 보증 조건에 해당하는 배터리·구동장치 문제는 제한 보증을 확인하고, 충돌·침수 등 사고 손상은 자동차보험 담보를 확인해야 합니다. 트림별 보증 기간과 주행거리, 용량 유지 조건은 차량의 실제 보증서를 기준으로 봐야 합니다.",
    why: "보증은 모든 성능 저하나 외부 손상을 보장하지 않으며 보험도 계약한 담보 범위까지만 적용됩니다. 중고차라면 보증 개시일과 누적 주행거리를 반드시 확인해야 합니다.",
    keyPoints: ["제조 결함 보증과 사고 보험을 구분", "트림별 기간·거리·용량 조건 확인", "중고차는 보증 개시일과 잔여 범위 계산"],
    rows: [["보증", "제조 결함·약정 조건", "차량 보증서와 진단 기준"], ["보험", "충돌·침수 등 사고 손상", "가입 담보와 면책 확인"], ["자비", "정상 마모·제외 항목", "예상 수리비와 대안 확인"]],
    checklist: ["차량 트림별 공식 보증 기간과 거리를 확인한다", "용량 유지 조건과 제외 사유를 보증서에서 읽는다", "보험의 배터리·전기차 관련 특약을 확인한다", "중고차는 최초 등록일과 누적 주행거리를 확인한다", "경고가 뜨면 임의 분해보다 앱으로 서비스 진단을 요청한다"],
    relatedSlugs: ["tesla-ev-maintenance-cost", "used-tesla-price-2026", "new-vs-used-tesla-2026"],
    answerSlugs: ["tesla-battery-warranty", "tesla-battery-degradation"],
    sourceKeys: ["teslaWarranty", "teslaRange", "fss"],
  },
  "tesla-hw3-vs-hw4-buying-guide": {
    category: "FSD·자율주행",
    title: "중고 테슬라 HW3·AI4 확인법과 구매 판단 기준",
    description: "하드웨어 세대 표기만 믿지 않고 차량 화면·제조 정보·카메라 구성·지원 기능을 확인해 중고차 가치를 판단합니다.",
    question: "HW3와 AI4 차이가 중고 테슬라 구매 가격을 바꿀 만큼 중요할까?",
    stage: "중고차·재고차 검토",
    needLevel: "보통 이상",
    intent: "운전자 보조 기능과 향후 소프트웨어 지원을 고려해 하드웨어 세대를 확인하려는 사람",
    answer: "하드웨어 세대만으로 차량 전체 가치를 결정하면 안 됩니다. 현재 제공되는 기능, 차량 상태, 보증, 가격 차이를 함께 보고 판매 설명과 차량 화면의 정보를 대조해야 합니다.",
    why: "기능 제공 범위는 국가 규제와 소프트웨어 배포에 따라 달라질 수 있고 미래 업그레이드는 확정되지 않을 수 있습니다. 사용하지 않을 기능 때문에 과도한 가격 차이를 지불하지 않는 것이 중요합니다.",
    keyPoints: ["판매 설명보다 차량 화면과 공식 정보 확인", "현재 사용 가능한 기능을 기준으로 가치 평가", "미래 기능을 확정 가치로 가격에 반영하지 않음"],
    rows: [["확인", "차량 정보·카메라·옵션", "실차와 판매 설명이 일치"], ["기능", "현재 국내 사용 가능 범위", "내가 실제 사용할 기능이 있음"], ["가격", "동일 상태 차량과 차이", "하드웨어 외 보증·이력 포함"]],
    checklist: ["차량 화면의 추가 차량 정보를 확인한다", "판매자가 적은 하드웨어와 옵션을 계약서에 명시한다", "현재 한국에서 제공되는 기능을 시승으로 확인한다", "동일 연식·상태의 다른 매물과 가격을 비교한다", "미래 기능 제공 약속은 공식 문서가 없으면 제외한다"],
    relatedSlugs: ["fsd-korea-status-2026", "fsd-subscription-vs-purchase", "used-tesla-price-2026"],
    answerSlugs: ["tesla-fsd-korea", "used-model-y-checklist"],
    sourceKeys: ["teslaAutopilot", "teslaSupport", "car365"],
  },
  "fsd-korea-status-2026": {
    category: "FSD·자율주행",
    title: "한국에서 테슬라 FSD를 이해할 때 구분해야 할 기능과 책임",
    description: "상품명과 실제 국내 제공 기능, 운전자 감독 의무, 규제·소프트웨어 업데이트 변수를 구분해 구매 전에 확인할 항목을 정리합니다.",
    question: "FSD라는 이름이 한국에서 완전 자율주행을 뜻하는 것일까?",
    stage: "옵션 구매 전",
    needLevel: "높음",
    intent: "광고명과 실제 차량에서 사용할 수 있는 운전자 보조 기능의 차이를 알고 싶은 사람",
    answer: "상품명만으로 완전 자율주행을 기대해서는 안 됩니다. 현재 차량에서 제공되는 기능과 운전자 감독 의무, 한국의 승인·배포 상태를 계약 당일 공식 화면과 약관에서 확인해야 합니다.",
    why: "지원 기능은 소프트웨어 버전과 차량 하드웨어, 국가별 규제에 따라 달라질 수 있습니다. 미래 제공 가능성보다 지금 사용할 수 있는 기능으로 구매 가치를 판단해야 합니다.",
    keyPoints: ["상품명과 실제 국내 제공 기능을 구분", "운전자 감독과 책임은 사라지지 않음", "계약 당일 차량·앱·공식 안내에서 기능 확인"],
    rows: [["명칭", "상품·패키지 이름", "기능 목록과 분리해 이해"], ["사용", "차량 버전·도로·날씨", "지원 조건과 제한을 확인"], ["책임", "운전자 감독·법규", "항상 개입 가능한 상태 유지"]],
    checklist: ["공식 주문 화면의 현재 기능 목록을 저장한다", "시승 차량과 구매 차량의 하드웨어·버전을 구분한다", "기능별 사용 조건과 운전자 의무를 읽는다", "한국에서 아직 제공되지 않는 기능은 가치에서 제외한다", "업데이트 뒤에도 릴리스 노트와 경고 문구를 확인한다"],
    relatedSlugs: ["tesla-hw3-vs-hw4-buying-guide", "fsd-subscription-vs-purchase", "tesla-purchase-process-for-beginners"],
    answerSlugs: ["tesla-fsd-korea"],
    sourceKeys: ["teslaAutopilot", "teslaSupport", "law"],
  },
  "fsd-subscription-vs-purchase": {
    category: "FSD·자율주행",
    title: "테슬라 FSD 구독과 일시불 구매를 비교하는 계산 기준",
    description: "월 구독료와 일시불 가격의 손익분기점뿐 아니라 보유기간, 차량 변경, 기능 제공 범위, 환불·이전 조건을 비교합니다.",
    question: "몇 년 보유할지 모를 때 구독과 일시불 중 무엇이 안전할까?",
    stage: "소프트웨어 옵션 결제 전",
    needLevel: "보통 이상",
    intent: "장기 사용 비용과 차량 교체 위험을 함께 고려해 FSD 결제 방식을 선택하려는 사람",
    answer: "단순 손익분기점은 일시불 가격을 월 구독료로 나눠 계산할 수 있지만, 실제 판단에는 보유기간과 기능 사용 빈도, 차량 변경 가능성, 이전·환불 조건을 넣어야 합니다. 현재 제공되는 기능을 일정 기간 시험할 수 있다면 구독의 선택권이 유리할 수 있습니다.",
    why: "요금과 판매 방식, 기능 범위는 바뀔 수 있으므로 과거 가격으로 장기 결정을 하면 안 됩니다. 결제 당일 앱과 주문 화면의 약관을 저장해야 합니다.",
    keyPoints: ["손익분기점과 예상 보유기간 비교", "차량 변경·이전·환불 조건 확인", "현재 제공 기능의 실제 사용 빈도를 기준으로 결정"],
    rows: [["구독", "초기 부담 낮고 중단 가능", "사용 빈도와 기능을 시험"], ["일시불", "초기 부담 크고 장기 사용 전제", "보유기간이 충분히 김"], ["공통", "기능 범위·약관·가격", "결제 당일 공식 조건 확인"]],
    checklist: ["현재 일시불 가격과 월 구독료를 같은 날 기록한다", "예상 차량 보유개월 수를 보수적으로 잡는다", "월별 실제 사용 횟수를 기록할 계획을 세운다", "차량 매각 때 옵션 이전·귀속 조건을 확인한다", "제공되지 않는 미래 기능은 계산에서 제외한다"],
    relatedSlugs: ["fsd-korea-status-2026", "tesla-hw3-vs-hw4-buying-guide", "tesla-3year-cost"],
    answerSlugs: ["tesla-fsd-korea"],
    sourceKeys: ["teslaAutopilot", "teslaSupport", "law"],
  },
  "tesla-contract-cancel": {
    category: "구매 가이드",
    title: "테슬라 주문 변경·취소 전에 확인할 비용과 일정",
    description: "주문 수수료, 차량 배정, 금융·보험 취소, 보조금 신청 철회, 환불 처리 순서를 주문 약관과 진행 단계별로 확인합니다.",
    question: "차량 주문을 취소하면 어떤 비용과 후속 절차가 남을까?",
    stage: "주문 변경·취소 전",
    needLevel: "높음",
    intent: "트림 변경, 출고 지연, 예산 변경으로 주문을 취소하거나 수정하려는 구매자",
    answer: "환불 가능 범위는 주문 당시 약관과 차량 배정·등록 진행 단계에 따라 확인해야 합니다. 주문 취소만으로 금융, 보험, 보조금 신청이 모두 자동 취소된다고 가정하지 말고 각 담당처에 철회 상태를 확인해야 합니다.",
    why: "차량 배정이나 등록이 진행된 뒤에는 시간과 비용이 더 발생할 수 있습니다. 전화 안내에만 의존하지 말고 앱·이메일·약관과 접수번호를 보관해야 분쟁을 줄일 수 있습니다.",
    keyPoints: ["주문 당시 약관과 현재 진행 단계를 먼저 확인", "금융·보험·보조금 철회를 각각 처리", "취소 요청과 환불 일정을 서면으로 보관"],
    rows: [["주문", "수수료·차량 배정·변경 가능", "주문 약관 기준 확인"], ["외부", "대출·보험·보조금", "각 기관의 철회 완료 확인"], ["환불", "금액·수단·처리 기간", "접수번호와 입금 내역 보관"]],
    checklist: ["주문 당시 약관과 결제 영수증을 찾는다", "앱에서 차량 배정과 등록 진행 상태를 확인한다", "취소 요청을 서면으로 남기고 접수번호를 받는다", "대출·보험·보조금 담당처에 별도로 철회한다", "환불 예정 금액과 날짜를 확인해 실제 입금과 대조한다"],
    relatedSlugs: ["tesla-purchase-process-for-beginners", "subsidy-refund-ownership-period-guide", "new-vs-used-tesla-2026"],
    answerSlugs: [],
    sourceKeys: ["teslaSupport", "law", "evPortal"],
  },
};

export const CANONICAL_GUIDE_SLUGS = Object.freeze(Object.keys(R));
export const CANONICAL_GUIDE_SET = new Set(CANONICAL_GUIDE_SLUGS);

function makeDecisionSection(spec) {
  return {
    title: spec.question,
    paragraphs: [spec.answer, spec.why],
    table: {
      headers: ["확인 항목", "살펴볼 내용", "판단 기준"],
      rows: spec.rows,
    },
  };
}

function makeChecklistSection(spec) {
  return {
    title: "구매 결정 전에 확인할 순서",
    paragraphs: [
      "아래 항목은 한 번에 결론을 내기 위한 목록이 아니라, 서로 다른 조건을 같은 기준으로 비교하기 위한 순서입니다. 확인한 날짜와 출처를 함께 적어두면 가격이나 정책이 바뀌어도 다시 판단하기 쉽습니다.",
      "차량 가격·보조금·요금·금융 조건은 변경될 수 있습니다. 최종 계약이나 신청 전에는 이 글의 기준일보다 현재의 공식 문서와 실제 견적을 우선하세요.",
    ],
    bullets: spec.checklist,
  };
}

/** 기존 글을 2026년 8월 편집 기준에 맞춰 대표 글로 재구성한다. */
export function rewriteGuide(guide) {
  const spec = R[guide.slug];
  if (!spec) return guide;

  const preserved = (guide.sections || [])
    .filter((section) => !/^(정리|결론|구매 전에 진짜)/.test(section.title || ""))
    .slice(0, 4);

  return {
    ...guide,
    category: spec.category,
    title: spec.title,
    description: spec.description,
    updatedAt: REVIEW_DATE,
    readTime: "10분",
    isNew: true,
    keyPoints: spec.keyPoints,
    readerNeed: {
      question: spec.question,
      stage: spec.stage,
      needLevel: spec.needLevel,
      intent: spec.intent,
    },
    sources: spec.sourceKeys.map((key) => SOURCES[key]),
    relatedSlugs: spec.relatedSlugs,
    answerSlugs: spec.answerSlugs,
    sections: [makeDecisionSection(spec), ...preserved, makeChecklistSection(spec)],
  };
}
